### ISSUE TITLE
Filter by Actor, Artist, Author, Brand or Title

### ISSUE THREAD

**Issue by WagnerW** [nager/Nager.AmazonProductAdvertising#106]
Hi TinoHager, sorry but because you do not include in your code the filter by Actor, Artist, Author, Brand or Title and SearchIndex, I'm putting in hand but I don't know if it's correct this way.

`  var searchItemRequest = new SearchItemRequest
            {
                Keywords = searchRequest.Keywords,
                Resources = searchRequest.Resources,
                ItemPage = searchRequest.ItemPage,
                SortBy = searchRequest.SortBy,
                Author = searchRequest.Author,
                SearchIndex = searchRequest.SearchIndex,
                BrowseNodeId = searchRequest.BrowseNodeId,
                PartnerTag = this._partnerTag,
                PartnerType = "Associates",
                Marketplace = $"www.{this._amazonEndpointConfig.Host}"
            };
`

**Comment by tinohager** [comment]
I'm not doing anything here right now. I have other tasks I have to do before.

**Comment by tinohager** [comment]
Brand and Title done (Pull https://github.com/tinohager/Nager.AmazonProductAdvertising/pull/109)

**Comment by WagnerW** [comment]
Ok but unfortunately I can no longer use PAAPI 4 OR PAAPI 5 Amazon revoked my access even selling and without any warning I am looking for another affiliation.
