### ISSUE TITLE
The request has not been correctly signed.

### ISSUE THREAD

**Issue by robdob** [nager/Nager.AmazonProductAdvertising#114]
Hi,

thank you for the great API, but could you please try and help me out.

I'm testing out you API using:

'var authentication = new AmazonAuthentication(accessKeyId, secretKey);
var clienttest = new AmazonProductAdvertisingClient(authentication, AmazonEndpoint.US, associateTag);
var result = clienttest.SearchItemsAsync("canon eos").GetAwaiter().GetResult();`

But I'm getting the following error when calling :clienttest.SearchItemsAsync("canon eos").GetAwaiter().GetResult();

"The request has not been correctly signed. If you are using an AWS SDK, requests are signed for you automatically; otherwise, go to https://webservices.amazon.com/paapi5/documentation/sending-request.html#signing."

Can you please let me know how I get around this, I have even created new accesskey and secretkey

thanks in advance,

**Comment by tinohager** [comment]
check your local clock on your host

**Comment by robdob** [comment]
I'm testing from my dev machine as localhost in debug more.,

what do you mean  by check my local clock,  can you please explain?

thanks,

**Comment by tinohager** [comment]
Maybe your clock is not current. https://time.is/<https://time.is/de/>

**Comment by robdob** [comment]
it says my clock is 1.8 secs behind I'm within the EST, would this be the reason?

**Comment by robdob** [comment]
Hi, do you know when you will have a version that will work or if there is anything that I can do on my end to get it to work?

Thanks,

**Comment by tinohager** [comment]
The library works without any problems. There must be something on their side. The best thing to do is to contact Amazon Support

**Comment by zhorakiev** [comment]
I am actually having the same issue. My location is West Coast USA and I am using AmazonEndpoint.US
