### ISSUE TITLE
Multi Item Lookup Advanced

### ISSUE THREAD

**Issue by roror409** [nager/Nager.AmazonProductAdvertising#122]
Can we get an example of a Multi Item Lookup in an Advanced version?  Also in the old version, you used AmazonWrapper as a way to get any errors from Amazon.  Is there an equivalent to the AmazonWrapper in this new version?  Thank you.

**Comment by tinohager** [comment]
The error message is always in the response

https://github.com/nager/Nager.AmazonProductAdvertising#multi-item-lookup
