### ISSUE TITLE
Product Description

### ISSUE THREAD

**Issue by roror409** [nager/Nager.AmazonProductAdvertising#123]
I can't seem to find the product description with this new version.  With the previous version Nager we would do something like this: 

foreach (var ed in item.EditorialReviews)
                {
                    string descrip = ed.Content;

                }
But now this information doesn't seem to be available when doing a Multi Item Lookup.  AWS information on this data can be found here: 
https://docs.aws.amazon.com/AWSECommerceService/latest/DG/RG_EditorialReview.html

**Comment by tinohager** [comment]
https://webservices.amazon.com/paapi5/documentation/migration-guide/pa-api-40-to-50-mapping.html

![image](https://user-images.githubusercontent.com/8215186/77104181-e52fd580-6a1b-11ea-8775-f8cc81af16f0.png)
