### ISSUE TITLE
GetItemsAsync Status= WaitingforActivation

### ISSUE THREAD

**Issue by roro409** [nager/Nager.AmazonProductAdvertising#124]
When running the GetItemsAsync to attempt to get multiple ASINs at once I never receive a response with data.

var authentication = new AmazonAuthentication(amzId, amzSec);
            //var client = new AmazonProductAdvertisingClient(authentication, AmazonEndpoint.US, "nager-20");
            var client = new AmazonProductAdvertisingClient(authentication, AmazonEndpoint.US, amzTag);
            string[] asinArray = asins.ToArray();
            //var result = client.GetItemsAsync(new string[] { "B00BYPW00I", "B004MKNBJG" });
            var result = client.GetItemsAsync(asinArray);

When I view the debugger after the GetIemsAysnc is run I can see result showing the following: 

Status = WaitingForActivation
Method = null
Result = Not yet computed

This happens whether I am using my own array or using the array directly in the example code.

**Comment by tinohager** [comment]
you miss the await  before GetItemsAsync

**Comment by roro409** [comment]
I've got a ton of synchronous methods leftover from the Amazon 4.0 API.  I'm short on time and can't convert it over to synchronous right now, which is what needs to be done to use await.  I imagine others might be in the same situation with the 5.0 upgrade so I'm going to leave this workaround here for anyone that might need it in the future.  If you run it the following way you can get it to run in a synchronous method but you can't access the error dialog.  

var result = client.GetItemsAsync(asinArray).Result;
