### ISSUE TITLE
Add GetBrowseNodes operation

### ISSUE THREAD

**Issue by ma-hartma** [nager/Nager.AmazonProductAdvertising#125]
Implement the GetBrowseNodes operation
https://webservices.amazon.com/paapi5/documentation/getbrowsenodes.html

**Comment by Jammasternam** [comment]
Hi,

Thanks for the good work. I noticed the Sales Rank in BrowseNodes always return 0. Is this a bug? Or am I doing something wrong.

var searchRequest = new SearchRequest
            {
                Keywords = "9780060004873|9780999120842",
                SearchIndex = SearchIndex.All,
                Resources = new[]
                {
                    "Images.Primary.Medium",
                    "BrowseNodeInfo.BrowseNodes",
                    "BrowseNodeInfo.WebsiteSalesRank",
                    "ItemInfo.ExternalIds",
                    "ItemInfo.Title",
                    "ItemInfo.ByLineInfo",
                    "ItemInfo.ManufactureInfo",
                    "ItemInfo.ProductInfo",
                    "ItemInfo.Classifications",
                    "Offers.Listings.Price",
                    "Offers.Listings.MerchantInfo"
                },
            };

**Comment by ma-hartma** [comment]
Hi @Jammasternam, 

You are trying to use the SearchItemsAsync method, which I think I didn't change with my pull request. 
Anyways, I've tested the same values as you did in my solution and You're right. The response coming from Amazon actually has SalesRanks and our serialized objects don't, so there seems to be a bug.
Have you found this error with the version from my fork or with the currently available NuGet package?

I'd recommend you to open an own issue for the SearchItemsAsync operation and the bug you found.
