### ISSUE TITLE
Overall Sales Rank Return 0

### ISSUE THREAD

**Issue by Jammasternam** [nager/Nager.AmazonProductAdvertising#127]
Edit: To be more specify. i am talking about the WebsiteSalesRank

> https://webservices.amazon.com/paapi5/documentation/browsenodeinfo.html

-----------------------------------------------------------------------------------------------------

Thanks for the good work. I noticed the Sales Rank in BrowseNodes always return 0. Is this a bug? Or am I doing something wrong. Both SearchItemsAsync and GetItemsAsync have this issue.

Exampe:
var searchRequest = new SearchRequest
{
Keywords = "9780060004873|9780999120842",
SearchIndex = SearchIndex.All,
Resources = new[]
{
"Images.Primary.Medium",
"BrowseNodeInfo.BrowseNodes",
"BrowseNodeInfo.WebsiteSalesRank",
"ItemInfo.ExternalIds",
"ItemInfo.Title",
"ItemInfo.ByLineInfo",
"ItemInfo.ManufactureInfo",
"ItemInfo.ProductInfo",
"ItemInfo.Classifications",
"Offers.Listings.Price",
"Offers.Listings.MerchantInfo"
},
};

**Comment by Jammasternam** [comment]
Any update on this?

**Comment by tinohager** [comment]
Add WebsiteSalesRank
