### ISSUE TITLE
SearchRequest Resources - Resource have wrong value error

### ISSUE THREAD

**Issue by Jammasternam** [nager/Nager.AmazonProductAdvertising#128]
I got the "**Resource have wrong value**" error when I include the following:

- Offers.Listings.Availability
- Offers.Listings.DeliveryInfo
- Offers.Listings.ProgramEligibility

Example:
```
Resources = new[]
                    {                        
                        "BrowseNodeInfo.BrowseNodes",
                        "BrowseNodeInfo.BrowseNodes.SalesRank",
                        "BrowseNodeInfo.WebsiteSalesRank",
                        "ItemInfo.ExternalIds",
                        "ItemInfo.Title",
                        "ItemInfo.ByLineInfo",
                        "ItemInfo.ContentInfo",
                        "ItemInfo.ManufactureInfo",
                        "ItemInfo.ProductInfo",
                        "ItemInfo.Classifications",
                        "Offers.Listings.Condition",
                        "Offers.Listings.Price",
                        "Offers.Listings.SavingBasis",
                        "Offers.Listings.MerchantInfo"

                        // ----- cause resource have wrong value error -----
                        //"Offers.Listings.Availability",
                        //"Offers.Listings.DeliveryInfo",
                        //"Offers.Listings.ProgramEligibility",
                    },
                };
```

**Comment by tinohager** [comment]
Can you please add a full example?

**Comment by Jammasternam** [comment]
`public static async Task ProcessSearchItemRequest()
 {
            var authentication = new AmazonAuthentication("", "");
            var client = new AmazonProductAdvertisingClient(authentication, AmazonEndpoint.US, "");
var searchRequest = new SearchRequest
                {
                    Keywords = "9780060833022|9780060833138",
                    SearchIndex = SearchIndex.Books,
                    Resources = new[]
                    {
                        "BrowseNodeInfo.BrowseNodes",
                        "BrowseNodeInfo.BrowseNodes.SalesRank",
                        "BrowseNodeInfo.WebsiteSalesRank",
                        "ItemInfo.ExternalIds",
                        "ItemInfo.Title",
                        "ItemInfo.ByLineInfo",
                        "ItemInfo.ContentInfo",
                        "ItemInfo.ManufactureInfo",
                        "ItemInfo.ProductInfo",
                        "ItemInfo.Classifications",
                        "Offers.Listings.Condition",
                        "Offers.Listings.Price",
                        "Offers.Listings.SavingBasis",
                        "Offers.Listings.MerchantInfo",

                        // ----- cause resource have wrong value error -----
                        "Offers.Listings.Availability",
                        "Offers.Listings.DeliveryInfo",
                        "Offers.Listings.ProgramEligibility",
                    },
                };

                var result = await client.SearchItemsAsync(searchRequest);
}`
