### ISSUE TITLE
Cant Upgrade To 2.1.0

### ISSUE THREAD

**Issue by nafberger** [nager/Nager.AmazonProductAdvertising#136]
I am trying to update to 2.1.0, from 1,0,26 cant do it it says that it makes a downgrade on something. but the old code is pointing to an old system and I can't get it to work. can u help me,

it causes problems all over my old projects 

what is the trouble

please

**Comment by nafberger** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1107	Version conflict detected for Microsoft.AspNetCore.WebUtilities. Install/reference Microsoft.AspNetCore.WebUtilities 2.2.0 directly to project WebApi to resolve this issue. 
 WebApi -> Integration.AmazonCore -> Nager.AmazonProductAdvertising 2.1.0 -> Microsoft.AspNetCore.WebUtilities (>= 2.2.0) 
 WebApi -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.AspNetCore.WebUtilities (>= 2.1.1 && < 2.2.0).	WebApi	C:\Users\Naftaly\Source\Repos\inventory-fba2\WebApi\WebApi.csproj	1	



Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1107	Version conflict detected for Microsoft.Extensions.Primitives. Install/reference Microsoft.Extensions.Primitives 2.2.0 directly to project WebApi to resolve this issue. 
 WebApi -> Microsoft.AspNetCore.WebUtilities 2.2.0 -> Microsoft.Net.Http.Headers 2.2.0 -> Microsoft.Extensions.Primitives (>= 2.2.0) 
 WebApi -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.Extensions.Primitives (>= 2.1.1 && < 2.2.0).	WebApi	C:\Users\Naftaly\Source\Repos\inventory-fba2\WebApi\WebApi.csproj	1	


Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1107	Version conflict detected for Microsoft.Extensions.Primitives. Install/reference Microsoft.Extensions.Primitives 2.2.0 directly to project WebApi to resolve this issue. 
 WebApi -> Microsoft.AspNetCore.WebUtilities 2.2.0 -> Microsoft.Net.Http.Headers 2.2.0 -> Microsoft.Extensions.Primitives (>= 2.2.0) 
 WebApi -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.Extensions.Primitives (>= 2.1.1 && < 2.2.0).	WebApi	C:\Users\Naftaly\Source\Repos\inventory-fba2\WebApi\WebApi.csproj	1	


Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1107	Version conflict detected for Microsoft.Extensions.Primitives. Install/reference Microsoft.Extensions.Primitives 2.2.0 directly to project WebApi to resolve this issue. 
 WebApi -> Microsoft.AspNetCore.WebUtilities 2.2.0 -> Microsoft.Net.Http.Headers 2.2.0 -> Microsoft.Extensions.Primitives (>= 2.2.0) 
 WebApi -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.Extensions.Primitives (>= 2.1.1 && < 2.2.0).	WebApi	C:\Users\Naftaly\Source\Repos\inventory-fba2\WebApi\WebApi.csproj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1107	Version conflict detected for Microsoft.Net.Http.Headers. Install/reference Microsoft.Net.Http.Headers 2.2.0 directly to project WebApi to resolve this issue. 
 WebApi -> Microsoft.AspNetCore.WebUtilities 2.2.0 -> Microsoft.Net.Http.Headers (>= 2.2.0) 
 WebApi -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.Net.Http.Headers (>= 2.1.1 && < 2.2.0).	WebApi	C:\Users\Naftaly\Source\Repos\inventory-fba2\WebApi\WebApi.csproj	1

**Comment by tinohager** [comment]
sorry i can't help you over some log lines. I only see some dependency problems.

**Comment by nafberger** [comment]
Hi Tino. it seems like your project targets net.core 2.2 and I have a net core 2.1 project. so how do I proceed? I am not sure whats the trouble is, I used your work 3 years ago.  very old version but if I use it now it seems to be pointing to a non-existent amazon web service endpoint. sorry for haggling you, can you please clarify on how to use your very useful library in a net.core 2.1 project? big big thanks

**Comment by nafberger** [comment]
u know tino, I really resent the fact that u ignore my question. why can't you help another human being socially distanced here in the frigid new york? crawling out from the long winter which kind of doesn't want to leave us, haha that same winter is now coming to you, hope the winters in Aussie are not that depressing like here in new york. anyway, please please please, can we have a conversation please to straighten this thing up. huge thanks
