### ISSUE TITLE
ItemInfo.ExternalIds and BrowseNodes.WebsiteSalesRank Always Return NULL

### ISSUE THREAD

**Issue by Jammasternam** [nager/Nager.AmazonProductAdvertising#138]
Example:
var itemResult = await client.GetItemsAsync("B000FC13AO");

https://www.amazon.com/dp/B000FC13AO
- ItemInfo.ExternalIds is null <-- 9780061749131
- BrowseNodes.WebsiteSalesRank is null <-- 1869 as of 5/11/2020

**Comment by iocasilan** [comment]
Need to add resource ItemInfo.ExternalIds for it to show:
`var itemRequest = new ItemsRequest
            {
                ItemIds = new[] { "B07VDD85XJ" },
                Resources = new[]
                {
                    "Images.Primary.Large",
                    "ItemInfo.ExternalIds",
                    "ItemInfo.Title",
                    "ItemInfo.Features",
                    "Offers.Listings.Price"
                }
            };
            var result = await client.GetItemsAsync(itemRequest);`
