### ISSUE TITLE
Missing "BrowseNodeInfo.WebsiteSalesRank" resource string for AmazonProductAdvertisingClient.GetItemsAsync

### ISSUE THREAD

**Issue by ShamilS** [nager/Nager.AmazonProductAdvertising#142]
public async Task<GetItemsResponse> GetItemsAsync(params string[] itemIds)
        {
            var request = new ItemsRequest
            {
                ItemIds = itemIds,
                Resources = new[]
                {
                    "BrowseNodeInfo.BrowseNodes",
                    "BrowseNodeInfo.BrowseNodes.Ancestor",
                    "BrowseNodeInfo.BrowseNodes.SalesRank",
                    "BrowseNodeInfo.WebsiteSalesRank",  // <= missing code line

                    "Images.Primary.Small",
                    "Images.Primary.Medium",
                    "Images.Primary.Large",
                  ....

**Comment by tinohager** [comment]
Use this method if you need an other resource collection
https://github.com/nager/Nager.AmazonProductAdvertising/blob/9fdb77392138e8bf4b26f6f3813f6af453545d13/src/Nager.AmazonProductAdvertising/AmazonProductAdvertisingClient.cs#L233
