### ISSUE TITLE
The request was denied due to request throttling.

### ISSUE THREAD

**Issue by techiesalman** [nager/Nager.AmazonProductAdvertising#146]
**Current Version:** 2.1.2

**Current Behvaiour:**
Error is coming, not receiving the product response. I have just created my Access key and Secret key to call Product Advertising API but I am receiving an error in response whenever I am calling the API from my local project. Error is,  "**The request was denied due to request throttling. Please verify the number of requests made per second to the Amazon Product Advertising API.**"

I have verified and I found that I am not making multiple requests. I have used your sample code only. Also, I googled and came to know that after creating the Access and Secret key one has to wait for 48 hours. So do I need to wait for 48 hours or I am missing something else on this.

Any information on this would be of great help to me.

**Expected behavior:**
It should have returned the response where I have seen the product details

**Code:**
var authentication = new AmazonAuthentication("myAccessKey", "mySecretKey");
var client = new AmazonProductAdvertisingClient(authentication, AmazonEndpoint.IN, "jugaadhai-21");
var result = await client.SearchItemsAsync("canon eos");

**Comment by tinohager** [comment]
As of January, 2019 – Amazon has now placed restrictions and limitations on who gets access to the API. Basically, you MUST have qualified sales attributed to API links within the previous trailing 30 days in order to prevent your API access from being revoked or limited (throttled).

**Comment by techiesalman** [comment]
> As of January, 2019 – Amazon has now placed restrictions and limitations on who gets access to the API. Basically, you MUST have qualified sales attributed to API links within the previous trailing 30 days in order to prevent your API access from being revoked or limited (throttled).

@tinohager What does qualified sales means? In last month I made around 100$ and 241 items have been ordered using my Amazon associate. While generating Credentials for PA API it was written on that page "In order to qualify for requesting access to PA API, you will need an associate account, you will have to complete 3 qualifying sales in the first 180 days and you will have to comply with the Operating Agreement. Once your account is approved as an associate account, you will see a 'Request for PA API access' button below. You can click the button to get access to PA API."

Seeing this it seems like I am eligible, don't know what's missing or what I am doing wrong?

**Comment by tinohager** [comment]
Have you try contact amazon over the contact form?
![image](https://user-images.githubusercontent.com/8215186/98664828-27ab7700-234b-11eb-90fa-bc6b03b86081.png)

**Comment by techiesalman** [comment]
I have contacted them and the response which I received from them is not of much help. 

![ReplyFromAmazon](https://user-images.githubusercontent.com/37684962/98670803-445ea380-2379-11eb-8ea8-e7d186804743.PNG)

After the above email from Amazon, I replied **"I have attached one image in which I am not able to see PA-API transactions. Maybe it is because I have enabled PA API today only.
As you can see in the image, in the last 30 days we made somewhere around 100$. Am I still not qualified for using PA API?. Can you please check into my account and let me know."**

After my above mail, last mail which I  received in that they were telling they are not equipped to provide any technical support or answer the queries related to Product Advertising API. They provided me some resources like the Getting started link, Scratchpad link, Detailed Documentation link, etc.

I am going to ask this question in the Amazon developer forum also. Let's see what I will get in response from there

**Comment by zhorakiev** [comment]
Same issue: The request has not been correctly signed

**Comment by techiesalman** [comment]
@tinohager I wanted to let you know that API started working successfully by default. Somewhere I read it takes 48 hours once you activate your token key. So I used to daily open my project and check it and glad it worked. Your code is working fine buddy.

Thank you.
