### ISSUE TITLE
unexpected character error

### ISSUE THREAD

**Issue by VolkiTheDreamer** [nager/Nager.AmazonProductAdvertising#149]
Hello, when i run the sample code, it just gives the following error.

unexpected character encountered while parsing value: <. Path '', line 0, position 

here is my code

static void Main(string[] args)
        {
            fetch();
            Console.ReadKey();
        }

        static async void fetch()
        {
            try
            {
                var authentication = new AmazonAuthentication();
                authentication.AccessKey = "my access key";
                authentication.SecretKey = "my secret key";

                var client = new AmazonProductAdvertisingClient(authentication, AmazonEndpoint.TR, "nager-20");
                var result = await client.GetItemsAsync("B00BYPW00I");
                Console.WriteLine(result);
                Console.ReadKey();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.ReadKey();
            }
        }

**Comment by tinohager** [comment]
hi, you can download the source code from here and debug it. I don't have access data for the Turkish Amazon endpoint.

**Comment by VolkiTheDreamer** [comment]
Thanks, i've modified the code but still doesn't work. i think the problem is that i dont qualify as an associate yet.
