### ISSUE TITLE
SearchRefinements return null

### ISSUE THREAD

**Issue by weberinfosp** [nager/Nager.AmazonProductAdvertising#152]
Hi, my api is not returning the "SearchRefinements" resource it is always null, I did a test with scratchpad da Amazon and everything is ok, the result follows, thanks
 ```
"SearchRefinements": {
   "BrowseNode": {
    "Bins": [
     {
      "DisplayName": "Administration, Business and Economy",
      "Id": "7872854011"
     },
     {
      "DisplayName": "Art, Cinema and Photography",
      "Id": "7841296011"
     },
     {
      "DisplayName": "Crafts, Home and Lifestyle",
      "Id": "7841521011"
     },
     {
      "DisplayName": "Self-Help",
      "Id": "7841720011"
     },
     {
      "DisplayName": "Biographies and Real Stories",
      "Id": "7841731011"
     },
     {
      "DisplayName": "Science",
      "Id": "7841795011"
     },
     {
      "DisplayName": "Computer, Computing and Digital Media",
      "Id": "7842641011"
     },
     {
      "DisplayName": "Chronicles, Humor and Entertainment",
      "Id": "7843925011"
     },
     {
      "DisplayName": "Right",
      "Id": "7874340011"
     },
     {
      "DisplayName": "Education, Reference and Didactics",
      "Id": "7842837011"
     },
     {
      "DisplayName": "Engineering and Transport",
      "Id": "12764254011"
     },
     {
      "DisplayName": "Erotic",
      "Id": "7843058011"
     },
     {
      "DisplayName": "Sports and Leisure",
      "Id": "7842741011"
     },
     {
      "DisplayName": "Fantasy, Horror and Science Fiction",
      "Id": "7841775011"
     },
     {
      "DisplayName": "Gastronomy and Cooking",
      "Id": "7872552011"
     },
     {
      "DisplayName": "History",
      "Id": "7843068011"
     },
     {
      "DisplayName": "Comics, Mangas and Graphic Novels",
      "Id": "7842710011"
     },
     {
      "DisplayName": "Children",
      "Id": "7844001011"
     },
     {
      "DisplayName": "Youths and Teens",
      "Id": "7841279011"
     },
     {
      "DisplayName": "LGBT",
      "Id": "7843064011"
     },
     {
      "DisplayName": "Literature and Fiction",
      "Id": "7872687011"
     },
     {
      "DisplayName": "Medicine",
      "Id": "7874461011"
     },
     {
      "DisplayName": "Cop, Suspense and Mystery",
      "Id": "7872829011"
     },
     {
      "DisplayName": "Politics, Philosophy and Social Sciences",
      "Id": "7873971011"
     },
     {
      "DisplayName": "Religion and Spirituality",
      "Id": "7874675011"
     },
     {
      "DisplayName": "Novel",
      "Id": "7882388011"
     },
     {
      "DisplayName": "Health and Family",
      "Id": "7882415011"
     },
     {
      "DisplayName": "Tour and Travel Guides",
      "Id": "7882554011"
     },
     {
      "DisplayName": "English and Other Languages",
      "Id": "7882627011"
     }
    ],
    "DisplayName": "Department",
    "Id": "BrowseNodeId"
   },
   "OtherRefinements": [
    {
     "Bins": [
      {
       "DisplayName": "Kennedy Ryan",
       "Id": "Kennedy Ryan"
      },
      {
       "DisplayName": "Lily Freitas",
       "Id": "Lily Freitas"
      },
      {
       "DisplayName": "Kimberly Mascarenhas",
       "Id": "Kimberly Mascarenhas"
      },
      {
       "DisplayName": "Aline Padua",
       "Id": "Aline Padua"
      },
      {
       "DisplayName": "Mauricio de Sousa",
       "Id": "Mauricio de Sousa"
      },
      {
       "DisplayName": "D.A. Lemoyne",
       "Id": "D.A. Lemoyne" ``

```

**Comment by tinohager** [comment]
please add a code example

**Comment by weberinfosp** [comment]
Hi TinoHager, in my tests I was using "SearchIndex = Books" and it only returned null, when I change it to "All" it starts to return data, when I do the same test by Scratchpad it returns all data including by author "OtherRefinements"

`"SearchIndex": "Books",
 "PartnerTag": "wwnaweb-20",
 "PartnerType": "Associates",
 "Marketplace": "www.amazon.com.br",
 "Operation": "SearchItems"`

`var searchRequest = new SearchRequest
            {
                ItemPage = page,
                BrowseNodeId = null,
                SearchIndex = SearchIndex.Books,
                Resources = new[]
                {
                   "BrowseNodeInfo.BrowseNodes",
                    "BrowseNodeInfo.BrowseNodes.Ancestor",
                    "BrowseNodeInfo.BrowseNodes.SalesRank",

                    "Images.Primary.Small",
                    "Images.Primary.Medium",
                    "Images.Primary.Large",

                    "Images.Variants.Small",
                    "Images.Variants.Medium",
                    "Images.Variants.Large",

                    "ItemInfo.ByLineInfo",
                    "ItemInfo.Classifications",
                    "ItemInfo.ContentInfo",
                    "ItemInfo.ContentRating",
                    "ItemInfo.ExternalIds",
                    "ItemInfo.Features",
                    "ItemInfo.ProductInfo",
                    "ItemInfo.TechnicalInfo",
                    "ItemInfo.Title",
                    "ItemInfo.TradeInInfo",

                    "Offers.Listings.Availability.MinOrderQuantity",
                    "Offers.Listings.Availability.MaxOrderQuantity",
                    "Offers.Listings.Availability.Message",
                    "Offers.Listings.Availability.Type",
                    "Offers.Listings.Condition",
                    "Offers.Listings.Condition.SubCondition",
                    "Offers.Listings.DeliveryInfo.IsAmazonFulfilled",
                    "Offers.Listings.DeliveryInfo.IsFreeShippingEligible",
                    "Offers.Listings.DeliveryInfo.IsPrimeEligible",
                    "Offers.Listings.LoyaltyPoints.Points",
                    "Offers.Listings.MerchantInfo",
                    "Offers.Listings.Price",
                    "Offers.Listings.ProgramEligibility.IsPrimeExclusive",
                    "Offers.Listings.ProgramEligibility.IsPrimePantry",
                    "Offers.Listings.Promotions",
                    "Offers.Listings.SavingBasis",
                    "Offers.Summaries.HighestPrice",
                    "Offers.Summaries.LowestPrice",
                    "Offers.Summaries.OfferCount",

                    "ParentASIN",
                    "SearchRefinements"
                }
            };
            
            var result = await client.SearchItemsAsync(searchRequest);`

**Comment by weberinfosp** [comment]
[https://1drv.ms/u/s!AsxsQEKkH-Kjk8BEa6s9FFRW2V1Ifw](url)

**Comment by weberinfosp** [comment]
![Capturar](https://user-images.githubusercontent.com/37640888/122476916-56eb2c00-cf9d-11eb-80e2-817e566eb276.PNG)

**Comment by weberinfosp** [comment]
working, thank you very much Tinohager
