### ISSUE TITLE
IsBuyboxWinner missing from Offers.Listings

### ISSUE THREAD

**Issue by edmacdonald** [nager/Nager.AmazonProductAdvertising#153]
https://webservices.amazon.com/paapi5/documentation/offers.html#listings

https://github.com/nager/Nager.AmazonProductAdvertising/pull/151

**Comment by tinohager** [comment]
@edmacdonald please add an example c# code

**Comment by edmacdonald** [comment]
@tinohager Done.

**Comment by tinohager** [comment]
I have publish a new version, thanks
